sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      
    packages:
      - cmake
      - cmake-data
      - g++-7
      - libboost-all-dev
      - valgrind
      - libperlio-gzip-perl
      - libjson-perl

before_install:
  - export CXX="g++-7"
  - export CC="gcc-7"
  - g++-7 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls
  
script: 
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - GCOV="gcov-7" COVERALLS_FLAGS="" ./deps/CMakeUtils/travis/doCoverage.sh
