sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - cmake
      - cmake-data
      - g++-8
      - libboost-all-dev
      - valgrind
      - lcov

before_install:
  - export CXX="g++-8"
  - export CC="gcc-8"
  - g++-8 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls

script:
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - ./deps/CMakeUtils/travis/doCoverage.sh
