sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      
    packages:
      - cmake
      - cmake-data
      - libboost1.55-all-dev
      - valgrind


before_install:
  - export CXX="g++-6"
  - export CC="gcc-6"
  - g++-6 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls
  
script: 
  - ./buildFromDeps.sh
  - cd Build
  - make test
  - ctest -T Memcheck
  - cd ..
  - COVERALLS_FLAGS="-e src/publisherSpeed.cpp -e src/dummy.cpp" ./deps/CMakeUtils/travis/doCoverage.sh
