sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      
    packages:
      - cmake
      - cmake-data
      - g++-9
      - libboost-all-dev
      - valgrind
      - libperlio-gzip-perl
      - libjson-perl

before_install:
  - export CXX="g++-9"
  - export CC="gcc-9"
  - g++-9 --version

install:
  - ./buildDeps.sh
  - pip install --user cpp-coveralls

script:
  - GCOV="gcov-9" COVERALLS_FLAGS="--verbose" ./deps/CMakeUtils/travis/doCoverage.sh
